try {
    throw "error";
} catch (e:Dynamic<T>) {}